#+TITLE: <2025-12-16 k>


Időben kezdődött. Tímea nem volt. Áron kötőhártya gyulladás.
Kati Andris Zoli Fertődön.

Jóska jön az intézetire. Nem kell a fiához mennie.

El nem végzett munka hasznossága.

* Power
Napirend előtt. A powerbank volt a kérdés. Géza látta számlát.
Azon volt a laptophoz

Kocka, vissza is tud táplálni. Napelemről tölthető.

Modulos aksi.

powercube

Szigetszerűen használhatod.

PowerMax 2400 pro. Kínei csoda.

Holfuy szenszora

* Kitüntetés
Mondtam, hogy Misinek inkább büntetés, Pista bácsi kapott.
Van-e valakinek jubileuma.

Jóska talán 58-as.

Milyen díjak vannak?

Kiss Marcit felvetették, de nem tudtam.

A lehetőségeket meg kell ragadni, hogy folyamatosan beterjesztik.
A listákat nézegetni.

* Utazási kedvezmények
Mindenki vegye át! Zsuzsa talán az illetékes.

* TÉR
Aki kapott felhívást menjen át! Lehet változtatni. Rajta. Géza nem változtatott
a javaslatán.

Erdőrezervátumban, BorderEye-ból is lesz pénz.

* BorderEye
NKFIH-s ígéret, hogy hosszabbítják.

* Gumis
Még nem ment az átutalás.

* Tantárgytematika feltöltés
Fogadóóra, Diplomamunka, Szakdolgozat tematika kitöltése.

* CV vizsga
Ki kell írni azt is. Hosszas megbeszélés a CV működéséről.

* Karácsony
Géza exkuzálta magát. Én később jövök.

* Egyéb
** Telefon, nyomtatás
Nem megy a telefon mellett a net és a nyomtatás Primusz Pnél,
Tominak sem megy a nyomtatás.

Moodle weboldalt sem éri el Primusz P.

Telefonhoz van leírás. Géza küldi.
** Laborok
Új rendszerben marad a profil. A hallgatók alkotnak.

Belépnek egymás fiókjába.

Excelt most nyitom meg először.

RRF moodle képzések vannak.
** Kornél bútora
Kisteherautó szerdán (XII. 17.)  lesz. Négy embernek kell kimennie.
