#+TITLE: <2026-01-27 k>

* Jelen
** Helyben
- KiGé
- HoTi
- BrGá pedagógiai továbbképzés csak benézett.
- SzBo
- KiBa
- PrPé a diplomatervezők között
- SzÁr
- BaTa
- ZKKA
- KaPé
** Online
- CzKo
- HeAn
- GrZo beteg
** Nincs

* Félév előkészítése
Órarend elkészült. Van-e óhaj sóhaj.

A régi kódú út is ki lett írva.

** Tantárgyi követelmények
Tantárgyi követelmények feb 2. 8.00-ig feltölteni.
Tamás Fruzsinának.

QR kód az intézeti hírdetőn.

Kötelező tartalmi elemek!

Külső előadók. Lechnertől jönnek. Feb 24, 25, 26.
26-án déltől előadás a Nagyméretarányún. 3 óra előadás.

Rab András

Gribovszki Zoltán Bódis Gábor és Szabó Ádám.

SzÁr Hadházi András geoinformatikai szakmérnök vadgazda GIS program.

Pete Viktória viszi a tárgyat.
Mokos Béla ingatlan.
Leica Paulusz Márk.

** Szakdolgozat és diplomatervek
Kutatási asszisztensek végzik. Február 27-ig.

- Kanizsai Botnd
- Amie
- Petrás Gábor 11 éves.
- Osváth Gergő

Korábbi táblázatba beírni.
GKI szakdolgozat diplomavédők táblázatba.

** Földmérő záróvizsga
Bazsó Tomi
Pomóthy Panna Cézárban dolgozik
Benyő Attila
Újpesti Krisztián a múltkoriból
Orosz Kamilla
Erdei Dávid

** Buszigény
Február 6 8-óra.

Buszigény sablon

Hidegvíz 2 Fertődre 1

** Szabadság
Február 1-éve lezár. Forms űrlapon.

Vannak alkalmazások, amik jók.
* Vadgazda aláírása

Vadgazda hallgató aláírását valaki beírta, Nem tud kimozdulni otthonról.


* Speciális támogatások
Feladat a speciális támogatásokról jelentést kell leadni a dékáninak.

2025 évben melyikben mi történt.

Egy-egy bekezdés a projektekre.

OTKA-t beírtuk és az agrárminisztériumira egy mondatot.

* Kitüntetések
Lehet javaslatot tenni február 4-ig föld napja ápr 22-ig.
ProNatura emlékplakett.

* Pro Cerevisia
Az intézet söre.

* Géza a jövő héten nem lesz
Toyotát megjáratja.

Hétfőn a Suzuki szervízbe megy, 10:30-ra. Más használja a suzukit?

Táblázatban senki sem volt. A

* Garázs kulcs
Kinél van?
- intézetnek a táblában
- GrZo
- ZKiKa
- HeAn

* Képegyeztetés
Délután 3-tól NRRC laborban. Agisoft csak a GT-ben.

AgiSoft szürke, hivatalos egyetemi licenc. Korábbi válotzatban nem volt
online ellenőrzés.

Agisoft saját gépre.

GT-ben lehet. Meghajtón anyagok.

* Labor állapot
Mi legyen a GT-vel. Öreg gépek... Talán 5 évesek.

Idei beruházási tervben vannak informatikai fejlesztések?

A számítógép árak elszálltak.

Az RRF-ben kapunk gépeket.

Felhő számítógépet bérelni.

NetControl Szászi Tomi nevén volt. Gyakorlat tartásnál hasznos.

* Fogadóórák beírása
Be kell írni. Nem fizetős óraadókat is beírni, másik csatlakozó.

* Egyebek
** HunEdu
Introduction of RemoteSensing.
** Botond beszámol
Versenyen mi volt?
Hó nem volt. Dél Tiroltól visszább. Műhavas pálya.
10-12. klasszikus és szabad stílusú.
** Agrármin
GrZo: Havas repülést elvetettük.
Objektumok látszanak.

Terepmodell kell akkor a hó nem segít.

Törzsfelismeréshez jó. Még havazni is fog.
** Kökény Gergő
Lombtalan repülés. Február 5-én előzetesen repülés.

** GT 116
3 óra és szerda délelőtt eredmény nézés 1.5-2 óra.

** ETK
Geomatika szekció hétfő délután 13:30 4-esben

** Jövő hét
Nem lesz értekezlet. Konferencia.
