#+TITLE: <2026-09-15 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- PrPé
- KiBa
- SzÁr
- BaTa
- KaPé

** Online

** Nincs
- ZKKA úton
- GrZo úton
- HeAn úton
- BrGá strang csere
- CzKo Rothban előadáson

* Bevezetés
Családias légkör.

* Kitűzés & SEN
Sátor kitűzése.

Lapos rendezvény. Kevesen voltak.
SEN jobb lett volna a második hét végén. CV után.
Tegnap szemeszter nyitó lötyögés.

Ünnepek.

* Félév kezdések
** Tantárgyi követelmények
Csinálni!

** CV-s hét
Minimum két alkalom.

** Külső előadók
Holnap határidős. Ha van még ötlet írjuk be még.
Géza is megnézte.
Rab András nagy cirkusz volt.

** Buszigények
Lezárva. Remélhetőleg nem maradt ki semmi.

* Szenátus
Ülés. Bemutatkozott a kuratórium. Sarki kamera. Bemutatkozást nem lehetett hallgani.

* Gábor megjött
* Folyt
Új vezetőknek bármi
* Összdolgozói
Kettes terem, Bálint kezdte, beszámolók. Index cikk.
Országos szinten 98% kuratórium csere. Nálunk javasolták, elfogadták.
Kifutása az átadásnak nyitott. Talán nem lesz költségvetés.

Rabi Horváth Andrea bemutatva.

Bálint hangsúlyozta az adminisztratív ügyek változása miatt nem minden folyamat megy.
Várják a véleményeket. Korábban volt egy levél, de ha van nehézkes folyamat,
akkor írásban jelezzük.

** Gépjárművek
Lesz egy fél állású gépjármű előadó. Kari autókkal foglalkoznak. Autót elkértek,
lejárt műszakival.

Ne legyen az, hogy hívnak, hogy ide-oda vigyük az autót.

Toyota friss műszaki, Szuzuki 2028.

Szuzuki után cégautóadó, matrica, műszaki, központi keretből fizetik.
Ha álmunk van, akkor konzultáljunk.

** 2027 évi beszerzési terv
Lehet, hogy holnapra kell. Jobb, ha több minden össze van szedve. Ha valami bekerül,
akkor az félig sínen van.

Ideiben szintezhők bent vannak. Tomi beszélt Forgóval és felhívja. Új árat ad.
Elvileg kari keretből, Géza 2.5 mio-ra emlékszik, Bálinttal beszélt Géza.

** Fórum rektori

** E ép.
Költözések.

** F ép.
Elkészült, nincs normális tanterem. Modern nagy közös helyiség.
Külön irodákat lefoglalták, ami tárgyaló lenne.

** C ép
Folyamatban közbeszerzés. Dec 31-ig kiköltöznek.

** Teremfoglaltás
Richárd kérdezte, de nem volt érdemi válasz.

** Nyelvi képzés
Most Augusztusban újítottak. Valami egész évfolyamos kurzusok.
A nyelvet csak EMK-n vezették be.

** Tanterv
Volt módosítás (előtárgyak), elfogadta a karitanács.
Előtárgyak változtak Gézánál. Nem tudják felvenni a CV-t.

** SZMSZv2
A változások miatt.

** Pannónia
UBC felemlegették. Benke Dénes és Lili voltak kint.

** Polgár Andris
Felvételik és hallgatói létszámok.
BSc kis emelkedés, MSc osztatlan kis emelkedés.
HKR aktualizálása. Módosulni fog véleményezni kell.
*** Földmérők
Tomi felvett elsősök 35 fő. Erdész nem is jött.

** 1956

** Kari Vacsi
Ottó pince dec 16.

** Munkavédelmi oktatás
Kis László. Vágvölgyi Andi az Egyetemi is.

Kullancs oltás a hallgatóknak is jár. A gyakorlatoknál a hallgatók
munkavédelmére figyelni.

Belesetet Vágvölgyi Andinak bejelenteni.

Sebesség korlátozás a Bajcsy porta előtt.

* Űj felvétel
Göncz Miklós belép. Részmunkaidős megbízás. Intézeti mérnök lesz, egyelőre szerződéses.

Benke Dénessel nem váltotta. Tanársegéid munkakörre még két félévig nem.
Van elképzélés? Lehet erdész, de földmérő is. Legyen meg a doktori felé az affinitása.

* Jégpálya
Szabó Péter nincs benne. Primusz P. beszélt vele.
Bozótírtás megvolt.

* Utas munka
Szili-Török György nem válaszolt.

* Laborok

** Digitális laobor
NRRC-s kártyára rá lehet íratni.

** GT116
Vásznak beszerezték, pénteken ki lett cserélve. Felszerelték.
Projektor nem tölti ki. Nagyobb képméret. Egyre több gép problémás.

Van amin nincs QGIS. Fenn kellene tartani a működés első 1, már 3
rendetlenkedik.

Sokszor kihúzkodnak. Múlt héten is lement a biztosíték.

** Felhasználóné
nrrclab, nrrclabor
nrrcoktato, heti9876

* BorderEye
Közbeszerzés megy.

Ha van érdeklődő cég!

Házik!

Szoftver folyamatosan frissül.

* Egyebek

