#+TITLE: <2026-05-26 k>

* Jelen
** Helyben
- KiGé
- HoTi
- CzKo drón közben jött Hunedu
- HeAn
- GrZo
- PrPé második kamara után jött
- BrGá
- BaTa késik
- ZKKA
- KaPé

** Online
- SzBo
- KiBa

** Nincs
- SzÁr

* TÉR
TÉRt már kezdés előtt előtt beszéltük.

Holnapig kellene kitölteni. 27 a határidő.

Az egyik legfontosabb. Egyedül Gábor kezdte el. Hogyan kell befejezni?
Belső hálózat.

Talán nem bonyolultabb, mint tavaly, de nem jobb...

Sok helyen elhangzott. A beígért fizetésemelés második részét nem kapjuk.
A megfelelő teljesítés mellett kapnak TÉR bért. Jelentősen nőtt a keret.
Lehet, hogy éles, de nagyon rossz.

Rossz besorolás esetén Gábor nem tudta átsorolni.

Projekt részvételt nem tudta hová írni. Harmadik misszió.

Oktatásnál Géza látta pontot, szabályzatnál is van pont, nem egyezik a kettő.
Nem világos, hogy mi számít bele, mi nem számít bele. Van videó, amit meg lehet
nézni. Nem egyértelmű óraszámot egyértelműsíti.

Lehet kiegészítéseket tenni. TÉR szabályzat van, hogy milyen pontok. Neptunból
jövő tárgyak OK.

EÁTK-s tárgyak harmadik misszióba beírható. E kapcsán volt nagy kavarodás.

* Kamara
Mérnöki kamara szakcsoport tovább képzés
28-án Ligneumban 10-15-ig. Soproni földmérőképzésről valamire.
Kornél lenne az illetékes.

* OEE
Lehetőség van az OEE vándorgyűlés részvételre.
Ez július 23-24-én.

Vízpótlást megnézni Nyíregyházán.

* MTA ülés
Május 15-én. Andris előadást tartott, Zoli a kerekasztal beszélgetésen vett részt.
Általánosságok voltak. Meteo jellemzők, felszín alatti vizek. BME hordalékmoztás,
kistavakról, Andris az erdőkről.

AM projekthez kapcsolódik. Nagy érdeklődés volt, de semmi konkrétum.

* Drónos konferencia
Szentpéteri László (régen trimble forgalmazó) vízi drónhajók voltak.
Jó volt a rendezvény, multi beam hajó.

Volt robotkutya.

Gábor Dénes drónos képzés. Kiegészítő MSc-s hallgatók mutattak be munkát.

* Kamara újra
Kornél hunedu projektről jött.
10–15 május 28. Hivatalos program.

Kornél szívesen tartja.

* 8. szemeszteres
Mini TDK-t rendeztek.

Referáltam június 25-ig.

* Miniszteri kitüntetések
Május 29-ig sok díj. AM. oklevelek, stb.
Van-e valaki aki a látótérbe került. Zoli Török Andrást tervezte.

* Roth
Jövő héten szerdán jönnek. Mikor tudjuk megbeszélni?

* Vizsgatáblázat
Vizsgaidőpontokat kitöltjük, van minta, hogy milyen vizsgalapot nyomtassunk.
A táblázat megvan, milyen vizsgalapot nyomtatunk.

* NRRC
Monitorok cseréje megtörtént. Megszűntek a problémák.

Szoftver frissítést jelezzük. Balázs megosztott dokumentumot küldött.
QGIS, autocad, notepad++, labormenedzser program.

ETK mindenféle felmérést végzett. Richárd szólt. GT116-ost elég
jelentősen befoglalták. Állásfoglalás.

Hosszabb távon a másfél labor elegendő-e? Legyen új labor?

Felújításra szorul, mondták a monitor cserénél. Előkerül a kivetítő, vászon
méret. Frissítés, újabb labor, meglévők fenntartása?

Kornél 50–50% lenne az igazságos. Ha nem megy, akkor saját
labor. GT116 ArcGIS nem megy, saját gépet telepített. Lenit média
laborok. ERTIs licenc, elvileg működik. Négy éve nem tudták
megoldani. Csak az informatikuson múlik, hogy megcsinálják. Működik.

win 11-re nem tudnak frissíteni? Nem akarnak. Két gép nem működik,
majd nyáron megnézik. Csak rá kellene szánni az időt.

Vannak gondok. Primuszék gépe és a bordereye gépeknél is volt benne
plusz hdd.

* HVV
Hidegvízvölgyi összetartás. Június 26-án péntek. HUN-RENeseknek is
kiküldeni.

Előtte 19-én MHT ülés. Zoli pénteken nyírogatta a füvet. Van mit össze
takarítani.

Köveskuti jelölte a fákat. Ősszel csinálják.


* Egyéb

** Kutatói nap
Június 15-én rövid bemutatás a vezetői részről.

Kornél az aktuális kutatásokról. Formson jelentkezés. Dina kiküldi az
EMK dolgozóknak.  Minél előbb. Június 3-ig jelentkezés. Kétszer kiküldeni
és 5-ig jelentkeznek. Régi poszter, A4-es lapok! 3–5 perces előadások, mi
érdekel...

** Felmérés terepgyakorlat
Melyik termet használhatnák? Holnap Géza 10-től lefoglalta vizsgára a gyakorlót.

** Földmérő szakos hallgatók fóruma
Ma délután 3–5-ig fórum. Mintatanterv, tantárgyi tematikák. Kari
szinten is 5 hallgató jött el.

** Akkus fúró
Lehetne használni. Tominál lehet?

** Rektori kinevezések
Meghosszabbítja a kuratórium december 31-ig. Valszeg intézetigazgatókét.

** TÉR
csináljuk! Van a forms is!
