#+TITLE: <2026-05-05 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- CzKo
- KiBa
- HeAn
- PrPé később
- SzÁr
- BrGá később
- BaTa
- ZKKA
- GrZo EP írás
- KaPé

** Online

** Nincs

* Félév vége
Emailben!

Vizsgaidőszak. Végzősök jövő hét hétfőn!
Tanulmányútra mennek.

Félév végi aláírások május 17 (május 8.)

Vizsgalapok. Vizsgaidőszak végén leadni a teljeset.

Online táblázat a vizsgaidőpontokkal.

* Védés beosztása
Május 15-ig. Június 16 (kedd). Áron helyettesít.

* Egészségpénztár
Szenátusi terembe 8–16 óráig. Sok gyerek személyi igazolvány szám, TB.

* Kerékpár
Szervíznél pénz a számlán.

* Emlékérmek
Darányi Ignác díj.

* Védések
Abdalrahman és Ferrat. Utóbbinak éppen meglett.
Ferrat korábban csinálta. Még egy koszovói hallgató van...

* BorderEye
Kari tanács után. Szenátusiban.

BorderEye tanfolyam kitöltés.

* AM támogatás
Rezervátum program keretében. Beszerzésre van tavalyról maradék,
ha össze lehet vonni 1.5 mio Ft.

Informatikai segéd pendrive, powerbank, külső vinyó.

Keret nem nagy, de jó ötletet szívesen lát.

Támogató okirat Gézánál is.

* Kisbuszfoglalás
Megváltozott a rendszer. Kit érint?

* Roth geodézia
Sereg Adrienn a geodézia felelőse. Június 3-án.

Megbeszélték, hogy kinek jó.

* OEE
Emlékerdő faültetés. Madarak és fák napja.

* Toyota
Május 22

Május 28 Győr-Moson vármegye mérnöki kamara kihelyezett ülés szeretnék, hogy
előadást tartsunk.

Javítás távirányító border eye.

* Egyebek
** Jankó konferencia
Befejeződött a hallgatók, utána a kollégák.

* Kornél 55
