#+TITLE: <2026-03-10 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- HeAn  
- KiBa
- PrPé
- SzÁr
- BrGá
- BaTa
- ZKKA
- GrZo
- KaPé
** Online
** Nincs
- CzKo a végére beért

* VERGA
Két időpont. Most csütörtökről-péntekre virradóan.

23-ról 24-re virradóan. hétfőről keddre.

Kinek jó megbeszélése? Pilóták.

** Nem lesz benzin?
Becsippantották a forgalmit.

** Döntés
Hétfőről keddre virradóan.

4T-hez lesz plusz aksi.

A héten mikor lehetne szakmai áttekintő nap.

Bemenet a zavarás miatt.

Megvannak a tapasztalatok. Mit kellett magasabban repülni?

* Mikrotanúsítvány adatok
Holnapig átnézni.

Sokszor előkerült.

Felvetettem a földmérőt. Fehérváron sok kolléga van.
Szakirányú továbbképzés beadva és elfogadva.

Jogszabályi háttér, három melléklet. Kialakításának elvei.

ESG alapján.

Drónos fotó feldolgozás?

* Britt valami
Agrárfelsőoktatás?

* Hidegvíz-völgyi házra dőlő fák
Rádőlt fákat. 20 db fa rádőlt 850 e Ft bruttó. Meg tudjuk oldani?
Mennyire égető. Bálintnál megkérdezi.

Felmerült a használat tanszék?

* Papp Gábor levele
Ligneum konferencia.

Geodézia célú UAV

* Lechneresek
Ideadták az elérhetőségét Paulik Sándor erdőmérnöknek.
Felső rendű szintezés DNA03 Komplex szerelés és anyagok
2.5 Mio műszer, 1.5 mio építési anyagok.

Géza, Tomi szerint kicsit túl van árazva. Földfúró, mérőeszköz

Pioneer bányászati fúrógép.

Sok, ha rugalmas, érdekes-e?

* HM rendezvény pénteken
Nem volt senki.

* Vízügyes erdészek
NRRC lenne az egyik lehetőség. Szerdán 4-esben geodézia.

* Lineum HUR-REN konferencia
Adrianre. Kornél innen jött.

* Tűzvédelmi márc 31.
Zolinak segíteni.
