#+TITLE: <2026-05-26 k>

* Jelen
** Helyben
- KiGé
- HoTi
- CzKo
- HeAn
- GrZo
- BrGá
- BaTa késik
- ZKKA
- KaPé

** Online
- SzBo
- PrPé
- KiBa

** Nincs
- SzÁr

* TÉR
TÉRt már kezdés előtt előtt beszéltük.

Holnapig kellene kitölteni. 27 a határidő.

Az egyik legfontosabb. Egyedül Gábor kezdte el. Hogyan kell befejezni?
Belső hálózat.

Talán nem bonyolultabb, mint tavaly, de nem jobb...

Sok helyen elhangzott. A beígért fizetésemelés második részét nem kapjuk.
A megfelelő teljesítés mellett kapnak TÉR bért. Jelentősen nőtt a keret.
Lehet, hogy éles, de nagyon rossz.

Rossz besorolás esetén Gábor nem tudta átsorolni.

Projekt részvételt nem tudta hová írni. Harmadik misszió.

Oktatásnál Géza látta pontot, szabályzatnál is van pont, nem egyezik a kettő.
Nem világos, hogy mi számít bele, mi nem számít bele. Van videó, amit meg lehet
nézni. Nem egyértelmű óraszámot egyértelműsíti.

Lehet kiegészítéseket tenni. TÉR szabályzat van, hogy milyen pontok. Neptunból
jövő tárgyak OK.

EÁTK-s tárgyak harmadik misszióba beírható. E kapcsán volt nagy kavarodás.


