#+TITLE: <2026-02-24 k>

* Jelen
** Helyben
- KiGé
- HoTi
- HeAn
- CzKo
- KiBa
- PrPé
- SzÁr
- BrGá
- BaTa
- GrZo
- KaPé
** Online
- SzBo Sepsiszentgyörgy távoktatás
** Nincs
- ZKKA szabin

* Köszöntő
Botond behívása.

* Vezetői fórum
** Stratégiák bemutatása
Célja csak a bemutatás.
Megvitatásra nem volt lehetőség.

Kari és egyetemi vezetés végig látogatja az intézeteket. Stratégiának
megfelően az éves tervek, lebontása. Megadtuk, mikor vannak az
értekezletek.

Március 13-án lesz a kuratóriumi ülés. Ha van észrevétel, mutatókon
lehet vitatkozni.  Irányvonalakban már nem lesz jelentős változás.

** KEKVA szerződés
KFSZ-nek hívják. Kekva Fenntartási Szerződés.
A lényege, hogy milyen létszám és paraméterek. Állami támogatás érdekében.
Hallgatói létszámot már elértük, nem kell növelni.

Mindenki munkáján alapulhat az Egyetem jövője. Nem elég ha egy-két
ember húz.  Intellektuális és hallgatói terek.

Versenyképes és fenntartható forrásteremtő képességgel rendelkező
egyetem. Jelenleg 85%-ot mondanak. Működési költség, kekva, hosszabb távon. Forrás teremtő képesség.

25%-ról 33%-ra nőtt az elvonás, de visszakapjuk.

- Multidiszciplináris k

Négy pont renszer. Kiválóság Lean szemlélet. Komoly válalati renszerben használják.
500 mio Ft bevétel, nemzetközi forrás bevonó képesség, Okos Erdő projekt kiemelve!
Megfelelő támogatás kellene. Gazdasági stabilitás.

Multidiszciplináris. Kutató csoportok megalakítása. Minimum 5 kutatócsoport 2030-ig.
Intézeti struktúrát áthidaló, külön forrásokat ér el. Támogatják. Idő eldönti.

Publikációs teljesítmény kiegyenlített a karok között. 2025-ben
jelentős visszaesés. Az egyetemen 3.6-ról 2.4-re!

Kampusz nemzetköziesítés.

Innovatív oktatás megerősítése. Három portfólió. Kicsiny de prémium. A
cél 50 negyven év alatt. Oktatás képzés.

Kristófiék szerveznek.

Külföldi hallgatók támogatása, Zöld fenntarthatóság. Működési
kiválóság, AI, workflow. Horváth és társai folyamt digitalizálása.

Első magyar lean egyetem. Mestertervek botanikuskert, épületek, stratégiai irányok.
A 2026-os feladattervezés ezzel a szemlélettel.

Át kell beszélni Bokodi Szabolcsékkal az excelt átbeszéljük.

Példa Polgár Andrásék ESG képzése.

Tóth Kázmér a hagyományok eltorzulnak. Katonai reguláció. Alkoholizmus.

Stummerné bántalmazás formája. Hallgató és oktató is. Cyber bulliing. Selmeci
hagyományokkal kapcsolatban mondta, vanna akik ezrét maradnak vagy mennek el.

Bálint közös célok, oktatás nemzetköziesítés.

Csipkó Csilla élmény fokozása. Nyelvi továbbképzés. Rektor a kötelező
orosz oktatás. Belső indíttatásból csinálni.

TÉR BÉR megemelése is előkerült. Nem értette, hogy ez alapján nagyon
fontos, hogy nem jutalom. A kereteket akarják jelentősen emelni, nem a
vezető dönti el, az értékelési renszer alapján, akit teljesít,
automatikusan megkapja.

Év végi jutalom teljesen más tészta lenne.

Rektort többen kérdezték, hogy melyik kari vezetőt támogatja. Aki a
startégia mögé beáll, azt. Közös megvalósítás.

GrZo: Hallgatók szintrehozása, tanulni tanítása. Ha vannak sikerélmények.
Tanulni tanítani és természettudományos.
Beszélgetés, technikusok.

Kornél: többet veszünk fel, de kevesebben végeznek.

* Kari tanács
- EMK beszámoló 2025 évről.
- Rob Kozak
- Tanulmányi rend
- Egyebek.

Üssék le a hetet, mostani tanulmányi rendet ne piszkálják. Jövőre
lesz-e ilyen?

* Informatikai igény
Ne a dékánt keresni a problémával. Intézeti szinten legyen összeszedve.
Péntek a határidő. Mindennapi munkaeszközökről van szó.

Rossz ez, elromlott az, milyen igény.

Herceg Andris írt bele. Külön eszközöket külön sorba. Nem jelent semmit,
de fontos, hogy meg jelenjenek az igények. A vászon is jó lehet.

* Jekatyerinburgiak látogatása
Uráli állami egytem Anna és Jurij docensek a kar intézeteit keresi. Facsi
stílusban ki lett osztva mikor.

Holnap 9:25– 10:10. 45 perc. Mit lehet bemutatni. Laborok.  Intézet
bemutató power point és három kutatási irány. Három témakör szerint.

Lehetne, hogy ide jöjjenek. Ha nem késnek. Géza csatlakozik. Angol
anyag van. Az egyes tanszékek részéről vannak-e újabb?

Mindhárom tanszékről. Külön diasor.

Jóska irodája.

Parcella.

* Lechner
Megköttetett a megállapodás, keretszerződés, műszerek használata külön
szerződés szerint.

Varga Norbert e-ing előadás. Át kellene tekinteni, hogy milyen témák,
milyen adatok, hogyan igényelni.

* Szakdolgozatok
Feladatkiírás múlt hét péntek.

* Papp Laci
Vérteserdőtől jönnek technikus kollégák. Több tematika kiajánlva és ők
választottak.

1.5 órás és négy órás is van.

* Földmérők világnapja
2026 márc 23-án hétfőn. Oltay terem Műegyetem. Iván Gyula a titkára,
meghív minket.

Botond elmehet bemutatni a SoilSens-es munkáját. Géza továbbítja a felkérést.
Tomi elmehet.

Szenátusi választás vezető megbízás eredmény.

* Buszigények
Facsi levele. 19 vagy 17 fős busz. Zoli egyeztetett.

* Egyebek
** Andris fényképezés
Jövő héten megcsinálják.
** Ünnep
Jóska is megérkezett.

Balázs!

** Közben még beszéltünk témákról
Volt a Mátyás király Vadaskert felmérés következik.
Brolly Gábor kérdezte Kanizsay Botondot.
