#+TITLE: <2026-09-01 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- CzKo
- HeAn
- PrPé
- KiBa elején online Kari Tanács után jött
- SzÁr
- ZKKA elején mért
- BrGá kicsit késve
- BaTa
- GrZo elején mért
- KaPé

** Online

** Nincs

* Bevezetés

* Félévkezdés
Múlt héten félévkezdéssel kezdték, de értekezlet után jött ki a levél.
Menjünk végig rajta. Tantárgyi követelmények szeptember 4-ig kell
elkészíteni.

Hiányzással kapcsolatban furcsa megfogalmazások.

CV-s vizsgák szeptember 7-ig. CV második oktatási hét. 14-től 18-ig.
Két alkalom első és utolsó napok!

Külső előadók szeptember 16-án 16 óráig. Múltkor már
beszéltek. Vannak-e további ötltek?

Eddig felírva:
- Gribovszi Kati
- Rab András
- Péterfalvi JÓzsef
- Kis Márton, ha vállalja.
- Kertész Péter
- Szabó Károly

Szakdolgozatok diplomatervek. Legyen a táblázat, ahol az emberek vannak.
Rabi Horváth Andreának. Intézet igazgató. Múltkori kiírás.

** Buszigény
Nem tantermi fluenta.

** Összdolgozói
11-én összdolgozói B ép 2-es terem. Kari tanács, szenátus,

** Gondok
Késői órák, GT foglaltság. Ebben a félévben már semmi, de később.
Gábor össze akar hívni egy megbeszélést a karok között.

* Repülés Velencei-tó
Szél megbillentette. Össze-vissza keringett. 1.5 m-ről lepottyant.
Negyedik akkunál ment tönkre. Jó összelátás.
Alján távmérő a por miatt?

Ott maradt a szenzor. Nincs adat feldolgozva. Track bejött.

Csütörtökön repültek. Ha lesz eredmény. Dudles. Kózdelmes lesz.
Dudles? Nem teszi ki a szoftver a log filet. Idő alapján párat összegyűjtött.
Hidegvíz-völgy. Határmentiség, nagy domborzat. Jó rálátás biztos lenne.

Balázs azért jön ma, hogy csütörtökön itt tudjon lenni. Áron is megy.

Áron doktori területe jó lenne. Neki jobb a Hidegvíz-völgy.

* Szenátusi válsztás
Intézeti után szavazzon mindenki.

A választás kritikus. Minden kategóriában egy-egy ember. Polgár András.
Első körben 50%-nál több szavazat, utána többségi szavazat.

Úgy van, hogy szavazásra 10-től. Személy azonosí.

* Kari tanács
Hivatalos alakuló ülése megvolt. Rektor úr is részt vett.
Megbízó levelek. 12+1 fő.

Sok minden a közeljövőre. Dékáni pályázat szeptember 23-án.  Október
26-ig. November 11-én bemutatni. Minden munkavállaló nyilváníthat
véleményt.

December 2-án új ügyrend, változhat a felépítés, de
mérséklet. Stratégia véglegesítése. Munkaterv. WorkFlow rendszer. A
kuratórium tagjait felsorolja.

* Tiny house
írott kő naturpark

* Pro Vértes
bevonni.

* Pályázat
4-es tanterem hibridizálása nem nyert.

* Egyebek
** Kornél
Interjút készít Pablo Gutyiérez, New Yorkban dolgozott. Sok
riport Magyarországon.

Tűz van a TAEG területén. Ács Norbi ment drónozni. Fertőszentmiklóson
gyorsan eloltották. Aug 14-én. Pont felhős volt, lehet látni az
úrfelvételen.

*** Konferencia
Tom Bear avar hidrológiai jellemzőiről. Debreceni Péter, Nagy Dani.
Szeptember 17én IUGG szervezés.

** Űrkütatási konferencia
Barta Vera az összekötő. Szeptember 9–11-én.
Földmegfigyelés érdekes lenne.

** 4-es
Új HDMI kábel lett.

** Pénteki megbeszélés
Vízvisszatgartás megbeszélés. Szeptember 4-én.

** Erdők éjszakája
Zoli megy víz, Erdőkárokról Csóka Gyuri.
Szép Juhásznénél.

Nemzetközileg meghatározott.

** Szeptember 23
András és Géza megy.

** Zoli ünneplése
