#+TITLE: <2026-06-23 k>

* Jelen
** Helyben
- KiGé
- HoTi
- CzKo
- PrPé kicsit késett
- KiBa késett
- BaTa
- BrGá
- ZKKA
- GrZo
- KaPé

** Online
- HeAn

** Nincs
- SzÁr szabin
- SzBo

* Bajnóczy Ádám
Kiegészítő információ
+36 30 385 4364

* Doktori védés
Megvolt.

* TÉR
Még zajlanak a dolgok.

Adatlapot kinyomtatni és aláírni. Tegnapelőttre.
Tímea segítségét kéri Géza.

Személyreszabott word dokumentum.

Teljesítmény értékelési lap. Oktatói és kutatói és szervezeti célokhoz hozzájárulás
3m (?n). Nem világos, hogy kinek kell kitölteni. Tavaly volt ilyen.

Nem oktató-kutató értékelés.

Párbeszéd is szétfolyt. Ki hol van?

Tomi holnap délután ér vissza.

Géza látja a dolgokat.

* Összdolgozói értekezlet
Csütörtökön 14:00-től a ligneumban.

GrZo, ZKissK, KaPé online.

Drónképzés miatt sokan. A jövővel kapcsolatos információ.

* BorderEye
Kik mennek, mikor?
Mára szállás foglalás. Négyen mennek a kari autóval.

Tesztrepülések.

Pár hete volt kocsi naptár mindenkinek.

* Hidegvíz
Feszített lett volna az alkalom.
Csütörtökre 9 és péntekre 8.5 péntekre több fél.
Most péntek elengedve, csütörtök vagy péntek.

Csütörtök lesz. További részletek később.

* Intézeti autók
Sokszor kritikán aluli állapotban voltak. Elintézték az egyik
kitakaríttatva, új ülés huzat. Kérés lenne, aki elviszik, próbálja
legalább olyan szép állapotban visszahozni.

Figyeljünk rá!

Kívülről le lehet mosni. Hátul a stihl akkumulátoros porszívó. Gyöngyi
irodájában az ablaknál jobb oldalon.

Folyamatos romlás. Benne vannak dolgok, csokis papír.

Sokért takarították ki.

** Toyota
Műszakival mivan? 
Tímea fölhívja Keresét.

Jún 29. Tápióbicske mérőpálya giroteodolitok.

Július 20. (hétfő) 8 órára kell vinni az autót.

* Hidegvíz újra
Gulyásleves lesz. Balázs jön. Lecsót csinál Tímea.

Gulyásleves, lecsó kenyér, víz intézet finanszírózza.
Többit amit szeretnénk, rágcsa. Ásványvizek a garázsban.

Külsősöknek szólni. Szita Reninek valszeg nem jó.

* Hőségriadó
Igyunk.

Szenátusi terem elérhető.

* Egyebek
Barabás Kende engedély. Mit csinált?

** Jankó
Végül is szólt-e valaki? Félévvel korábban végzetteknek szólt-e valaki.
Kanizsay...
Bizottság?

Oklevél? Multkor volt valami?

** Andris
Vassné Gál Dóra erdőrezervátum űrlapot kell kitölteni. 30-ig kell kitölteni.
Péntekre kitölti.

** Kari
Pályázatok. Kari diplomamunka pályázat. Senki nem tudja.
Lakatos Feri (kutatási rektorhelyettes) tud róla. Egyetemi dolog.

Tímea hozta vissza.

** NRRC programok
Aki használja, milyen programmal induljanak?

** Órarend
Órarend, rektori kör. A múlt héten az órarend elérhető legyen.

** Kínai delegáció
Ma délután 3-kor. Smart forestry duális képzés 60-90 hallgató.
BSc 4 éves. Előadnak. Ilyen formába. Már küldtek. Sandong.

** Tanévzáró
Ferencz Zoltán erdőkért felelős helyettes-államtitkár jön a tanévzáróra.

** Múlt heti képzés
Jól sikerült. Károly és Móni profik. Jól elvezetgették.
VR repülés.

** F épület
Holnap délután lesz az átadó. Ez lesz az igazi.
24-e (szerda) 15.30 óra Fuse

18.00 koktél.

Dress code könnyű nyári.
