#+TITLE: <2026-02-24 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- CzKo
- KiBa
- PrPé
- SzÁr
- BrGá
- BaTa
- ZKKA
- GrZo
- KaPé
** Online
- HeAn digitális oktásnál hívta be Géza
** Nincs



* HUNEDUs megbeszélés
Tudták kezelni?

Tágyleírás kidolgozva. Majd szólnak, hogy hogyan tovább?

* Intézetigazgatói
Beszámol.

KIM éves jelentést készítik a Dékániban.

Ma 10 órás határidő, a tavalyi beszerzéseket kell kitölteni. Tímea elkezdte csinálni.
Kérdés, hogy ha van beszerzés, naptári évben, ami a tavaliy évben beszerzésre került.

Infrastruktúrális jellegű beruházás.

Kar vette a kerítést.

Nagy drónbeszerzés.

** Szenátusi választás
- Nem oktató
- Vezető beosztású oktató

Egyesített erővel, biztos befutó.

Hogyan lesz a jelölés választás? Mindenki a saját emberünket választaná,
nincs kokrét név

** Markó Balázs
Közösségi médiában negatív hírek. Kreatív erdő kampány.
Rövid tájékoztatás.

** Épületek
KTI költözik. C épület kiköltözése napirenden. E épület kivitelezése
EU-s közbeszerzés 3 hónapos határidővel.

Tetőtér emelés.

F épületben nincsenek oktatási termek, közösségi terek vannak. Órarendet
nem nagyon segíti. Kiscsoportos gyakorlatok.

** Út nagy-gyakorlat
Amennyire jól értette Géza, a javasolt hét nem túl kedvező,
vizsgaidőszak csökken, nem lesz meg. Amit multkor mondtak. Noéminél
érdemes lenne tisztázni, a 13. oktatási héten május 4–8 héten
lenne. Geod nagy-gyakorlat előtt egy héttel.

Húsvét utáni hét, tavaszi szünet opció. Május 4–8-ig.

Primusz szerint az lett volna a jó megoldás, ha beleteszik (év elején).
Nem figyeltünk oda. Távolmaradás

** LECHNER
Megállapodás még kicsit húzódik.

Nem jönnek ide. Csütörtök továbbra is érvényes.

Lechnerrel együttműködésnek kemény feltételei vannak. Összes oktatási
anyaghoz hozzáférhessenek, szerződés aláírása nem történt meg. Még
vannak teendők.

** Bálint József
Meghalt, látta a hírt, de nem tudott semmit.
Feb. 28-án lesz a temetés.

** Digitális Oktatási Módszertani Csoport
Javaslat lenne, hogy minden egyes ember.

Úgy lenne jó összegyűjteni, hogy ki-mit csinált eddig, és ki mit
vállalna? Egy megcsinálva, egy folyamatban van. Mindenkit ösztönözni
az átállásra. Legyen egy összesítés.

** Stratégiák
Újra előkerültek. Lesz egy vezetői fóruma. Csütörtökön 10–12 óráig,
ahol bemutatják. A Ligneumban a vezetőségnek. Szerda estig leírni.

** Utas kollégák elutasították
Eutasítottak oktatási felkérést. Ösvények és padok tervezése.
Tuba Kati, milyen tárgy? Erdei padok és ösvények. Agrárerdészet.

B típusú tárgy elindult.

** Specializációk
Felmerült a választás a jövőben. Mennyire bízható a hallgatókra a
választás.  Bálint javasolta a műszaki szakiránnyal kapcsolatban a kar
fizeti a promóciós videókat.

Andris csinálna videót.

** Kutatás
TAEG megkeresés van, de Géza ne tudott érdemben egyeztetni, Erdészeti
Tudományos Konferencia beszámoló.

- Rezervátum
- Hidrológia
- Invázió
- Geoinformatika

** Máv-Gyesev
Mit tudunk vállalni, Vezetőség nem reagált, alacsonyabb
szint érdeklődött. Kapcsolatot felvették.

** V4 pályázat
Nem tudják micsoda.

** AI stratégia
Ki tudják küldeni. Minisztériumnak és Palkovicsnak ment jelentés.
Digitális okos erdő. Jó irány! Soproni-hegyvidék 1000 ha a 4000 ha-ból.

Hidegvíz-völgy fontos része lenne. Erdőrezervátum, Roth, sok adat.

** KEKVA
A szerződés tárgyalás alatt. Még nem lett leütve. Meghatározza az
Egyetem működését. Hallgatói létszám további növelése nem támogatott.
4000 körüli szinten tartani a létszámot.

Publikációk tekintetében némi csökkenés, egy héten belül leütik, hogy
mit fogadtak el.

** Pannónia Ösztöndíj
Továbbra is támogatják a használatát. EMK elköltötte, Többi karon 65 mio Ft
augusztus végéig, Oktatói tanulmányutak, de közösen a hallgatókkal is.

Sándor Márti és Facsi Uráli Egyetemen fogadókészség.

Augusztus végéig van-e ember ilyen tervekkel?

Áron Wageningennel kapcsolatban vannak a HUNEDU kapcsán. Idén ki
szeretne menni?

LEICA tanulmányút, amit terveztek megy-e?

** Munkatervek
Amit leadtunk, semmilyen visszajelzést, Egyeztetés, táblázatba
a paraméterek kézzel beírva. Informatikailag mit kezdenek.

* Autók
TAEG-es autót meghúzott. Tegnap küldtek valamit. Nem tuda, hogy mit
léptek vele.  Mienken van egy csík, matrica feljött és rohad alatta a
karosszéria.

Hátsó ajtóval lehet-e valamit kezdeni? Szürkévé érett műanyag lejött. Nem csak
kiakadt, lejött. Kipottyant egy darab.

Most kívülről nem nyitható. Mindennapi használatot
befolyásolja. Patent szemek elég gázok, le lehet szedni a burkolatot.

Tomi koordinálja.

Göncz Miklóssal mennének Kökény Gergőhöz.
*** Autópálya matrica
Toyotán nincs autópálya matrica. Géza Suzukival megy.
Toyotára kellene venni! Külön a tankolás, külön a matrica.
D2-eset veszünk. Idén kicsit drágább lett.
MOL kártyára meg lehet venni.

* Egyéb
** Nagyszkenner
Megérkezett az ajánlat. Fluentánál többbe kerül. Az autóra, hátizsákos,
drónra és sétálható.

17 M a kiegészítőkkel. 14 + 3 mio.

Kornélékéhoz hasonló, nagyobb, teljesítmény, jobb IMU, GNSS a hátizsákban.

** Számítógépek

GT-ben nem volt QGIS. Óra alatt visszatették a tanári gépre, van ahol
működik.

TopoXMAP frissítve. A vírusírtóra hivatkoztak.

Nem tud

DELL geo szervernek megszámláltak napjai.

Két fájlszerver is ott van az NRRC-ben. Áramszünet után felmerül.

* Alsfa
Közben Kornélnak mondtuk.
Dudles mérés, csapadék, talaj.
Adott neki minden adatot.

Nem küldte ki a levelet. Kurzusra írt. Szóltak a fejlesztőknek.

* Egyáb

** Onedrive megosztás
Nem megy, van egy megosztott mappa, bejön, kiír hibát.
Több probléma!

** AI
notebooklm.google.com

Mesterséges intelligencia google accountot igényel, prezentációt csinál.
Kari szintű.

Bálint is támogatná, hogy legyen.

** Külső oktatók, akiknek megadtuk a nevét
Esetükben az az eljárás, hogy
Rozmánnénak kellene elérhetőség.

Hadházi Balázs nincs benne. Email és telefonszám.

Vizsgáztatni kell-e? Senkinek sem.

Bódis Gábor és Szabó Ádám számát és emailjét megadtuk.
