#+TITLE: <2026-02-17 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- CzKo
- KiBa
- PrPé
- SzÁr
- ZKKA
- BaTa
- GrZo
- KaPé
** Online
- HeAn
** Nincs
- BrGá


* Nem érzékeny képanyag
Gellért tudja

* OTKA
Bérátterhelés.

* Teremfoglalás
Egy alkalmas vízügy.

Kiszorult Kornél a GT-ből.

* Félévkezdés
Órarendek letisztázódtak.
** Utas nagy-gyakorlat
** Komplex nagy-gyakorlat
június 15-19
** Természedvédő
június 1-5-ig.
** Záróviszga
Kik végeznek?
- Bazsó Tamás
- Orosz Kamilla
- Benyó Attila
- Erdei Dávid
- Pomóthy Panna
- Újpesti Krisztián
** Szakdolgozatok
Enyém 9.5

Koncentráljunk az aktuális félévre.

Február 27-re kiírás határidő. Tímea az illetékes.
* Ipari kapcsolatok
Ma 12 óráig határidős
Kapcsolattartó személyt ki lehet egészíteni.

Kiemelt szerződések, nagy frekvencia.
Ne duplázzák, darabszám, kiemelt partnerek.

Szakmai kapcsolat, ipari kapcsolat.
* Szakközepes hallgatók
Duális képzés, gyakorlati helyek.

Mindenféle kavarás után, tegnapra tényleg igénylünk-e és hány hallgatót?

Volt több megbeszélés.

Több megbeszélés volt, Botankert helyszín már van.
Középfokú nyári gyakorlat EÁTK keretében.
június második felétől július végéig.

Két fő. Nem nekünk kell fizetni, de valaki fizet érte.

* Bünni Egyetem
Egyetemi vezetés látogatást tett. Napokon belül pályázatot adnak be,
stratégiai partnerként be tudunk lépni.

Alapvetően magyar kőris ártéri erdőkben közép és déleurópában.
Veszélyeztetett faj, human activities, climate shift. Invazív patogénje van.
Távérzékelésnek lehet-e szerepe.

Átküldi. Ha valaki lát fantáziát. Vízgazdálkodással is lehet összefüggés.

ScanDanube project a neve.

* Földmérő minősítő bizottság
Tagot jelöltünk. Major Róbertet jelölnénk.
Tomi megfigyelő tagként vegyen részt.

Minimum öt év IRM gyakorlat. Ha Tomit elfogadnák? Gyula online becsatlakozott.

* Jövő héten LECHNER államhatárügyi osztály
Elméletileg kedden délutántól, szerdán.

Csütörtök délután. Térinformatikai menedzsmentről átjönnek.
Ingatlan-nyilvántartáshoz kapcsolódva!
1-től 3+ óra.

Lechnerrel együttműködésnek kemény feltételei vannak. Összes oktatási anyaghoz
hozzáférhessenek, szerződés aláírása nem történt meg. Még vannak teendők.

* Egészségügyi dobozok
NRRC-be felvinni. Látszó helyre felvinni.

* NRRC
NRRC-ben sípolt a szünetmentes, battery not connected.
Mi értelme van?

Van feszültség ingadozás. Egy hete hétfőn áramszünet. Sima bekapcsoló gombbal.

Egyet érdemes lenne rendbe tenni. Egy aksi 15 ezer forint minimum 10 van benne.
150-250 e Ft körüli.

Piros konnektorokat nem dugták be az informatikusok.

Nem lenne szabad lenni a piros szekrényt. Bajcsy portán van a kulcsa a
szünetmentesnek, de nincs a villanyszerelőnek kulcsa.

GT-ben is szekrényben kismegszakító.

** Szoftver
Balázs: OFFICE AutoCAD frissítve.
Több gép bekapcsolva maradt.

A régi laborszoftver ment. Rá tudsz nézni úgy, hogy nincs gond.

* Laborszoftver
Laborvezérlő szoftver.

Lemaradó hallgatók. Könnyebb segíteni.

NetControll2 van magyar forgalmazó SmallPress 110e gép 1 tanár 20 tanuló.

* Alsfa
Dudles mérés, csapadék, talaj.

Adatokat adunk. Lelkes. Eső és hó.
Talajos, kombinálni távérzékelési és talajvizsgálati módszereket.
Talajokhoz vett, felrakott, talajmikrobiológiai elemzéseket végezne.
Sipos Gyuri segít neki.

Kimegyünk vele. Minden hónapban.

* Agrárminisztérium
1,5 – 2 oldalas. Dokumentumot.
Topográfiai tantárgy. Légi lézeres modellből, precíz domborzatmodell.

* Barabás Kende
Másnál sem teljesít.

* Egyebek
** Kalicz Péter

