#+TITLE: <2026-06-09 k>

* Jelen
** Helyben
- KiGé
- HoTi
- SzBo
- HeAn
- PrPé
- KiBa
- PéJó
- CzKo megbeszélésen volt TÉR közben jött
- SzÁr megbeszélésen volt TÉR közben jött
- ZKKA
- GrZo
- KaPé

** Online

** Nincs
- BaTa
- BrGá szabi

* TÉR
Ez a legfontosabb.

Kornél, Tímea és Botond még egy értéket sem adott meg.

GGKI munkatársaknál senki nem töltött.

Oktatási pontok én nyertem.

** Párbeszéd adatlap
Zolitól lezárta. Egyeztetésnél be kell tenni. Nézzük meg a párbeszéd
adatlapot és akkor látja Géza. Ez van a leírásban.

** Lezárni
Zárjuk le!

** Hogyan számol?
Nem logikus.

Középiskolában és általánosban megszüntették a TÉRt.

* Botond védés
Holnap 12-kor. A épület karitanács terem.

* Nem mennek
Zichyújfaluba

* Közös kutatói nap
Hétfőn lesz.

* Beszámolók
22-még belefér azért lett oda téve.

* Szakdolgozat védés
Jövő hét kedden.

Külső bírálatok megjöttek?

* Záróvizsga
23-án kedden.

* Jankó
24-e lenne a Janóra a záróvizsga miatt.

Nagy áron megkérdezése.

* Ki hová megy
A drónos képzésre a kocsifutást rendezték.

* HUNEDU
Kornél reklámozza jövő hét hétfőn.

* Tájékoztatás kérése
Önálló válaszokat kérnek a rektoriból.

Humánerőforrás igény fejlesztés. Előléptetési és átsorolási javaslatok.
Új munkatár és teljes/rész munkaidős. Péntekig. Gördülő HR terv.

Vendégoktatók helyett alkalmazás a közgázon. Botondnak lejár, de kutatói
munkakörben alkalmaznák. Nem ismerjük a kereteket.

Kornél két embert hozna Benke Dénest is hozná. Be tudna szállni
oktatásba. Hasonlóan Áronhoz.

Dékánokat kérik, hogy a jövő félévi órarendeket tegyék közzé.

* Infó beszerzések
Laptopok.

GT és egy újabb labor felszerelése.

* Földmérő minősítő
Major Robi vesz részt, vele készül a szerződés.

* Egyéb
** Közös kutató
Kornél 11:55-tők bemutató Kar kutatási koncepció.

Utána pico-k. 3 perc 3-5 dia. Legérdekesebb.

ggki 15
tőlunk 11 (4-5 ERTI)

Szabó Marci jelentkezett?

Van egy részletes program a google driveon. EMK biztosít pogácsát.
** AM támogatás
Pályázat azonosítója legyen feltüntetve.

Géza vízpótlás a téma. Max 5 olal jelentés. Inkább szakfolyóirat.

Július végéig max 5 oldalas jelentések.

Géza Bencével egyeztetett LAIs ügyben.
** Andris ünneplése
